name: .NET

on:
  push:
    branches: 
      - 'feat/*'
      - 'feature/*'
      - 'hotfix/*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install nuke global tool
      run: dotnet tool install Nuke.GlobalTool --global
      
    - name: Restore & Build e & Tests
      run: nuke
